### ISSUE TITLE
Not running in ios, please review 

### ISSUE THREAD

**Issue by sadaqatdev** [driftboat/flutter_zoom#6] opened 2021-09-06 09:48 UTC
Showing Recent Issues
Undefined symbol: _OBJC_CLASS_$_MobileRTCSDKInitContext

Undefined symbol: _OBJC_CLASS_$_MobileRTC

Undefined symbol: _kMeetingParam_MeetingPassword

Undefined symbol: _kMeetingParam_Username

Undefined symbol: _OBJC_CLASS_$_MobileRTCMeetingStartParam4WithoutLoginUser

Undefined symbol: _kMeetingParam_MeetingNumber

**Comment by driftboat** [comment] 2021-09-06 10:13
Please check "NOTE for testing on the iOS simulator" in https://github.com/driftboat/flutter_zoom/blob/main/zoom/README.md#ios
On  iOS Simulator, Please run `flutter pub run zoom:unzip_zoom_sdk dev` to get " iOS Dev Zoom SDK "

**Comment by sadaqatdev** [comment] 2021-09-06 10:59
> Please check "NOTE for testing on the iOS simulator" in https://github.com/driftboat/flutter_zoom/blob/main/zoom/README.md#ios
> On iOS Simulator, Please run `flutter pub run zoom:unzip_zoom_sdk dev` to get " iOS Dev Zoom SDK 

thanks its working

**Comment by sadaqatdev** [comment] 2021-09-06 10:59
failed to initialised zoom sdk

**Comment by driftboat** [comment] 2021-09-07 02:50
Please make sure you have replaced the "your jwtToken" following this guild: https://github.com/driftboat/flutter_zoom/blob/main/zoom/README.md#example

**Comment by driftboat** [comment] 2021-09-17 01:22
Duplicate of #2

**Closed as completed** 2021-09-21 15:32 UTC
